### ISSUE TITLE
Failed at the bailbloc@1.1.3 postinstall script 'electron-builder install-app-deps'

### ISSUE THREAD

**Issue by scarf** [thenewinquiry/bailbloc#45]
i was trying to compile this on my linux server and getting the error below:

```
~/src/bailbloc/desktop$ npm install
npm WARN package.json bailbloc@1.1.3 No repository field.
npm WARN engine electron-builder@19.48.3: wanted: {"node":">=6.11.4"} (current: {"node":"4.8.7","npm":"2.15.11"})
npm WARN engine builder-util-runtime@3.3.1: wanted: {"node":">=6.0.0"} (current: {"node":"4.8.7","npm":"2.15.11"})
npm WARN engine electron-builder-lib@19.48.3: wanted: {"node":">=6.11.4"} (current: {"node":"4.8.7","npm":"2.15.11"})
npm WARN engine builder-util-runtime@3.3.1: wanted: {"node":">=6.0.0"} (current: {"node":"4.8.7","npm":"2.15.11"})
npm WARN engine xmlbuilder@2.2.1: wanted: {"node":"0.8.x || 0.10.x"} (current: {"node":"4.8.7","npm":"2.15.11"})
npm WARN engine xmlbuilder@2.2.1: wanted: {"node":"0.8.x || 0.10.x"} (current: {"node":"4.8.7","npm":"2.15.11"})
npm WARN optional dep failed, continuing 7zip-bin-mac@1.0.1
npm WARN optional dep failed, continuing 7zip-bin-win@2.1.1
npm WARN deprecated lodash-node@2.4.1: This package is discontinued. Use lodash@^4.0.0.
/
> electron@1.7.9 postinstall /home/scar/src/bailbloc/desktop/node_modules/electron
> node install.js

npm WARN optional dep failed, continuing 7zip-bin-mac@1.0.1
npm WARN optional dep failed, continuing 7zip-bin-win@2.1.1
npm WARN engine mime@2.0.3: wanted: {"node":">=6.0.0"} (current: {"node":"4.8.7","npm":"2.15.11"})

> rabin-bindings@1.7.4 install /home/scar/src/bailbloc/desktop/node_modules/electron-builder/node_modules/electron-builder-lib/node_modules/app-package-builder/node_modules/rabin-bindings
> prebuild-install || node-gyp rebuild

prebuild-install info begin Prebuild-install version 2.4.1
prebuild-install info looking for local prebuild @ prebuilds/rabin-bindings-v1.7.4-node-v46-linux-x64.tar.gz
prebuild-install info found local prebuild 
prebuild-install info unpacking @ prebuilds/rabin-bindings-v1.7.4-node-v46-linux-x64.tar.gz
prebuild-install info unpack resolved to /home/scar/src/bailbloc/desktop/node_modules/electron-builder/node_modules/electron-builder-lib/node_modules/app-package-builder/node_modules/rabin-bindings/build/Release/rabin-bindings.node
prebuild-install info unpack required /home/scar/src/bailbloc/desktop/node_modules/electron-builder/node_modules/electron-builder-lib/node_modules/app-package-builder/node_modules/rabin-bindings/build/Release/rabin-bindings.node successfully
prebuild-install info install Successfully installed prebuilt binary!

> bailbloc@1.1.3 postinstall /home/scar/src/bailbloc/desktop
> electron-builder install-app-deps

/home/scar/src/bailbloc/desktop/node_modules/electron-builder/out/builder.js:21
    var _ref = (0, (_bluebirdLst || _load_bluebirdLst()).coroutine)(function* (options, cancellationToken = new (_builderUtilRuntime || _load_builderUtilRuntime()).CancellationToken()) {
                                                                                                          ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at _load_builder (/home/scar/src/bailbloc/desktop/node_modules/electron-builder/out/cli/cli.js:80:23)
    at Object.<anonymous> (/home/scar/src/bailbloc/desktop/node_modules/electron-builder/out/cli/cli.js:118:81)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:140:18)
    at node.js:1043:3

npm ERR! Linux 3.2.0-4-amd64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v4.8.7
npm ERR! npm  v2.15.11
npm ERR! code ELIFECYCLE
npm ERR! bailbloc@1.1.3 postinstall: `electron-builder install-app-deps`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bailbloc@1.1.3 postinstall script 'electron-builder install-app-deps'.
npm ERR! This is most likely a problem with the bailbloc package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron-builder install-app-deps
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bailbloc
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls bailbloc
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/scar/src/bailbloc/desktop/npm-debug.log

```

**Comment by wgwz** [comment]
@scarf Could you try upgrading `node`? I noticed this in your error log:

```{"node":">=6.0.0"} (current: {"node":"4.8.7","npm":"2.15.11"})```

Let us know if you found something that works since!
